name: Build

on:
  workflow_call:
  push:
    branches: [ main, 0.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up .NET 6.0
      id: dotnet-setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: use .NET 6.0
      run: |
        dotnet new globaljson --sdk-version '${{ steps.dotnet-setup.outputs.dotnet-version }}'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build project
      id: build
      run: |
        dotnet build
