name: v0.x Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semantic version to release
        required: true
        type: string

jobs:
  release:
    uses: ./.github/workflows/release-workflow.yml
    with:
      branch: 0.x
      version: ${{ inputs.version }}
    secrets: inherit
